### ISSUE TITLE
Not properly responsive on mobile

### ISSUE THREAD

**Issue by matthewmccullough** [matthewmccullough/matthewmccullough.github.io#2]
@jordanmccullough Can you tell me what I need to change (you have collaborator permissions) on the stylesheet for it to have two nice lines for the header when shunk down to mobile size?

![image](https://cloud.githubusercontent.com/assets/24734/8068908/f51e7aa8-0eab-11e5-9669-4ffff410dcbf.png)

**Comment by jordanmccullough** [comment]
I'll take a look.

On Tue, Jun 9, 2015 at 2:32 PM, Matthew McCullough <notifications@github.com
> wrote:

> @jordanmccullough <https://github.com/jordanmccullough> Can you tell me
> what I need to change (you have collaborator permissions) on the stylesheet
> for it to have two nice lines for the header when shunk down to mobile size?
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/24734/8068908/f51e7aa8-0eab-11e5-9669-4ffff410dcbf.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matthewmccullough/matthewmccullough.github.io/issues/2>
> .
>



-- 
Jordan McCullough
GitHub Services
http://training.github.com

**Comment by matthewmccullough** [comment]
I know you are super busy, but if you point me in the right direction perhaps over the 4th of July weekend, I'd be very appreciative. I'm stuck without your brains. :smile:

**Comment by jordanmccullough** [comment]
Addressed via https://github.com/matthewmccullough/matthewmccullough.github.io/pull/3.
